name: CI Build Linux

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build CI
        run: |
          make arm_sdk_install
          make -j8

      - name: Collect files matching pattern
        id: collect_files
        run: |
          files=$(find obj -name "*.hex")
          echo "files=$files" >> $GITHUB_ENV

      - name: Upload release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.files }}
        
