name: CI Build Linux

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build CI
        run: |
          make arm_sdk_install
          make -j8

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: AM32-binaries
          path: |
            obj/*.hex
          retention-days: 7
          
      - name: Upload binaries to release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: obj/*.hex
        
